modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://"

[[mods]]
logoFile="assets/legacyskins/icon.png"
modId = "legacyskins"
version = "0.0.0"
displayName = "Legacy Skins"
authors = 'RedRain0o0, Jab125'
credits = ''
displayURL = "https://"
description = "l4j+cpm"

[[dependencies.legacyskins]]
modId = "neoforge"
mandatory = true
type="required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.legacyskins]]
modId = "minecraft"
mandatory = true
type="required"
versionRange = "1.21.1"
ordering = "NONE"
side = "BOTH"

[modproperties.legacyskins]
catalogueImageIcon="icon.png"
[[mixins]]
config="legacyskins.mixins.json"