modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/RedRain0o0/legacy-skins/issues"

[[mods]]
logoFile="assets/legacyskins/icon.png"
modId = "legacyskins"
version = "${deps.version}"
displayName = "Legacy Skins"
authors = 'RedRain0o0, Jab125'
credits = ''
displayURL = "https://modrinth.com/mod/legacy-skins"
description = "An addon for Legacy4J and Customizable Player Models that brings back the ability to choose skins!"

[[dependencies.legacyskins]]
modId = "neoforge"
mandatory = true
type="required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.legacyskins]]
modId = "minecraft"
mandatory = true
type="required"
versionRange = "1.21.1"
ordering = "NONE"
side = "BOTH"

[modproperties.legacyskins]
# Note, Catalogue's screen never opens, why is this here
catalogueImageIcon="assets/legacyskins/icon.png"
[[mixins]]
config="legacyskins.mixins.json"