# Dependencies
minecraft_version=1.20.1
fabric_api_version=0.92.5+1.20.1
clothconfig_version=11.1.136
yacl_version=3.6.6+1.20.1-fabric
legacy4j_repo_version=1.20.1-1.8.4-lts
factoryapi_repo_version=1.20.1-2.2.5
reborn_energy_version=3.0.0
# CPM versions
cpm_api_version=0.6.21
cpm_loader=Fabric
cpm_mc_version=1.20
cpm_runtime_version=0.6.21a
# Figura versions
figura_version=0.1.5+1.20.1
luaj_version=3.0.8
nv_websocket_version=2.14