# Dependencies
minecraft_version=1.21.4
neoforge_version=21.4.44-beta
clothconfig_version=17.0.144
yacl_version=3.6.2+1.21.4-neoforge
legacy4j_version=1.21.4-1.7.10+neoforge
factoryapi_version=1.21.4-2.2
# CPM versions
cpm_api_version=0.6.17
cpm_loader=
cpm_mc_version=1.21.4
cpm_runtime_version=0.6.19a

supported_minecraft_versions=1.21.4