# Dependencies
minecraft_version=1.21.8
fabric_api_version=0.131.0+1.21.8
clothconfig_version=19.0.147
yacl_version=3.7.1+1.21.6-fabric
legacy4j_repo_version=1.21.8-1.8.3
factoryapi_repo_version=1.21.8-2.2.6
reborn_energy_version=4.2.0
# CPM versions
cpm_api_version=0.6.24
cpm_loader=Fabric
cpm_mc_version=1.21.8
cpm_runtime_version=0.6.24a
# Figura versions
figura_version=0.1.5+1.21.4
luaj_version=3.0.8
nv_websocket_version=2.14

supported_minecraft_versions=1.21.7,1.21.8